all:
	g++ -c bin_image.cpp
	g++ -c core.cpp
	g++ -c enemy.cpp
	g++ -c font.cpp
	g++ -c input.cpp
	g++ -c main.cpp
	g++ -c physics_sprite.cpp
	g++ -c sound.cpp
	g++ -c sprite.cpp
	g++ -o WAGB -w bin_image.o core.o enemy.o font.o input.o main.o physics_sprite.o sound.o sprite.o -lSDL -lSDL_ttf

clean:
	rm bin_image.o core.o enemy.o font.o input.o main.o physics_sprite.o sound.o sprite.o WAGB